/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import com.mysql.jdbc.PreparedStatement;
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.function.Supplier;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
//import com.mysql.jdbc.Connection;

/**
 *
 * @author user
 */
public final class add_item extends javax.swing.JFrame {

    /**
     * Creates new form add_item
     */
    public add_item() {
        initComponents();
        getConnection();
        showDate();
        showTime();
        
    }
    
    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        date.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                time.setText(s.format(d));
            }

        }).start();
    }

    public Connection getConnection() {
        Connection con = null;

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stockmgt", "root", "");
            //JOptionPane.showMessageDialog(null, "connected");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(add_item.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "not connected");
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        product_name = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        details = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        warranty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        discount = new javax.swing.JTextField();
        txtlow = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1090, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Company Name");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 34, 140, 50));

        date.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        date.setForeground(new java.awt.Color(51, 51, 255));
        date.setText("date");
        jPanel4.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, 170, 30));

        time.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        time.setForeground(new java.awt.Color(0, 51, 255));
        time.setText("time");
        jPanel4.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 170, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, -1));

        jPanel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel2KeyPressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Product Name  :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 130, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Stock Level      :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 140, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Selling Price     :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 140, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Details      :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 100, 40));

        product_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 190, 40));

        price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 190, 40));

        stock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stockKeyPressed(evt);
            }
        });
        jPanel2.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 190, 40));

        details.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(details, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 310, 130));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 140, 40));

        btn_add.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_add.setText("Add Item");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel2.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 160, 40));

        warranty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        warranty.setText("0");
        warranty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                warrantyKeyPressed(evt);
            }
        });
        jPanel2.add(warranty, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 190, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Warranty         :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 140, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Discount         :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 140, 40));

        discount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        discount.setText("0");
        discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                discountKeyPressed(evt);
            }
        });
        jPanel2.add(discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 190, 40));

        txtlow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtlow.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlowKeyPressed(evt);
            }
        });
        jPanel2.add(txtlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 190, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Low Level      :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 140, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 1070, 370));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 500, 140, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 160, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        close();
        login lg = new login();
        lg.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        close();
        main mainpage = new main();
        mainpage.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        //ADD BUTTON 
        if (checkInputs()) {

            try {
                Connection con = getConnection();
                PreparedStatement ps = (PreparedStatement) con.prepareStatement("insert into products(product_name,stock,discount,price,warranty,details,low_level) values(?,?,?,?,?,?,?)");
                ps.setString(1, product_name.getText());
                ps.setString(2, stock.getText());
                ps.setString(3, discount.getText());
                ps.setString(4, price.getText());
                ps.setString(5, warranty.getText());
                ps.setString(6, details.getText());
                ps.setString(7, txtlow.getText());

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data added");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, "one or more fields are empty");
        }
        product_name.setText(null);
        stock.setText(null);
        price.setText(null);
        details.setText(null);
        discount.setText(null);
        warranty.setText(null);
        txtlow.setText(null);


    }//GEN-LAST:event_btn_addActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        product_name.setText(null);
        stock.setText(null);
        price.setText(null);
        details.setText(null);
        discount.setText(null);
        warranty.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void stockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockKeyPressed
        // TODO add your handling code here:
        if( evt.getKeyCode() == KeyEvent.VK_ENTER ){
            if (checkInputs()) {

            try {
                Connection con = getConnection();
                PreparedStatement ps = (PreparedStatement) con.prepareStatement("insert into products(product_name,stock,discount,price,warranty,details,low_level) values(?,?,?,?,?,?,?)");
                ps.setString(1, product_name.getText());
                ps.setString(2, stock.getText());
                ps.setString(3, discount.getText());
                ps.setString(4, price.getText());
                ps.setString(5, warranty.getText());
                ps.setString(6, details.getText());
                ps.setString(7, txtlow.getText());

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data added");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, "one or more fields are empty");
        }
        product_name.setText(null);
        stock.setText(null);
        price.setText(null);
        details.setText(null);
        discount.setText(null);
        warranty.setText(null);
        txtlow.setText(null);


        }
    }//GEN-LAST:event_stockKeyPressed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        // TODO add your handling code here:
        if( evt.getKeyCode() == KeyEvent.VK_BACKSPACE ){
            close();// back key
            main mainpage = new main();
            mainpage.setVisible(true);
        }
    }//GEN-LAST:event_jButton5KeyPressed

    private void jPanel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel2KeyPressed
        // TODO add your handling code here:///-backspace
        if( evt.getKeyCode() == KeyEvent.VK_BACKSPACE ){
            close();
            main mainpage = new main();
            mainpage.setVisible(true);
        }
    }//GEN-LAST:event_jPanel2KeyPressed

    private void warrantyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_warrantyKeyPressed
        // TODO add your handling code here:
        if( evt.getKeyCode() == KeyEvent.VK_ENTER ){
            if (checkInputs()) {

            try {
                Connection con = getConnection();
                PreparedStatement ps = (PreparedStatement) con.prepareStatement("insert into products(product_name,stock,discount,price,warranty,details,low_level) values(?,?,?,?,?,?,?)");
                ps.setString(1, product_name.getText());
                ps.setString(2, stock.getText());
                ps.setString(3, discount.getText());
                ps.setString(4, price.getText());
                ps.setString(5, warranty.getText());
                ps.setString(6, details.getText());
                ps.setString(7, txtlow.getText());

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data added");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, "one or more fields are empty");
        }
        product_name.setText(null);
        stock.setText(null);
        price.setText(null);
        details.setText(null);
        discount.setText(null);
        warranty.setText(null);
        txtlow.setText(null);


        }
    }//GEN-LAST:event_warrantyKeyPressed

    private void discountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountKeyPressed
        // TODO add your handling code here:
        //discount key pressed
        if( evt.getKeyCode() == KeyEvent.VK_ENTER ){
            if (checkInputs()) {

            try {
                Connection con = getConnection();
                PreparedStatement ps = (PreparedStatement) con.prepareStatement("insert into products(product_name,stock,discount,price,warranty,details,low_level) values(?,?,?,?,?,?,?)");
                ps.setString(1, product_name.getText());
                ps.setString(2, stock.getText());
                ps.setString(3, discount.getText());
                ps.setString(4, price.getText());
                ps.setString(5, warranty.getText());
                ps.setString(6, details.getText());
                ps.setString(7, txtlow.getText());

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data added");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, "one or more fields are empty");
        }
        product_name.setText(null);
        stock.setText(null);
        price.setText(null);
        details.setText(null);
        discount.setText(null);
        warranty.setText(null);
        txtlow.setText(null);


        }
    }//GEN-LAST:event_discountKeyPressed

    private void txtlowKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlowKeyPressed
        // TODO add your handling code here:
        if( evt.getKeyCode() == KeyEvent.VK_ENTER ){
            if (checkInputs()) {

            try {
                Connection con = getConnection();
                PreparedStatement ps = (PreparedStatement) con.prepareStatement("insert into products(product_name,stock,discount,price,warranty,details,low_level) values(?,?,?,?,?,?,?)");
                ps.setString(1, product_name.getText());
                ps.setString(2, stock.getText());
                ps.setString(3, discount.getText());
                ps.setString(4, price.getText());
                ps.setString(5, warranty.getText());
                ps.setString(6, details.getText());
                ps.setString(7, txtlow.getText());

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data added");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, "one or more fields are empty");
        }
        product_name.setText(null);
        stock.setText(null);
        price.setText(null);
        details.setText(null);
        discount.setText(null);
        warranty.setText(null);
        txtlow.setText(null);


        }
    }//GEN-LAST:event_txtlowKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new add_item().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JLabel date;
    private javax.swing.JTextField details;
    private javax.swing.JTextField discount;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField price;
    private javax.swing.JTextField product_name;
    private javax.swing.JTextField stock;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txtlow;
    private javax.swing.JTextField warranty;
    // End of variables declaration//GEN-END:variables
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    public boolean checkInputs() {
        if (product_name.getText() == null
                || stock.getText() == null
                || price.getText() == null
                || warranty.getText()==null
                || discount.getText()==null) {

            return true;
        } else {
            try {
                Float.parseFloat(price.getText());
                return true;
            } catch (Exception ex) {
                return false;
            }
        }
    }

}
