/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import com.mysql.jdbc.PreparedStatement;
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.function.Supplier;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class add_stock extends javax.swing.JFrame {

    /**
     * Creates new form add_stock
     */
    public add_stock() {
        initComponents();
        getConnection();
        Show_products_in_Jtable();
        showTime();
        showDate();
    }
    
    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        date.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                time.setText(s.format(d));
            }

        }).start();
    }
    
    public Connection getConnection(){
        Connection con = null;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stockmgt","root","");
            //JOptionPane.showMessageDialog(null, "connected");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(add_item.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "not connected");
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        newquantity = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtstock = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_products = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Back");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Log Out");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1090, 600));
        setPreferredSize(new java.awt.Dimension(1090, 600));
        setSize(new java.awt.Dimension(1090, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 580, 1090, 580));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Company Name");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 34, 140, 50));

        time.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        time.setForeground(new java.awt.Color(0, 51, 255));
        time.setText("time");
        jPanel4.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 170, 30));

        date.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        date.setForeground(new java.awt.Color(51, 51, 255));
        date.setText("date");
        jPanel4.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 170, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 110));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("Back");
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 110, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Price                   :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 180, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Product Id            :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 170, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Product Name       :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 180, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("New Quantity        :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 170, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Available Quantity  :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 170, 40));
        jPanel2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 220, 40));
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 220, 40));

        newquantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newquantityKeyPressed(evt);
            }
        });
        jPanel2.add(newquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 220, 40));
        jPanel2.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 220, 40));
        jPanel2.add(txtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 220, 40));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Cancel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 190, 40));

        jTable_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "product_name", "price", "stock", "details"
            }
        ));
        jTable_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_productsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_products);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 370));

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("Update");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 190, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1070, 380));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 150, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 510, 160, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        close();
        login lg = new login();
        lg.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close();
        main mainpage =new main();
        mainpage.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_productsMouseClicked
        int index = jTable_products.getSelectedRow();
        showitem(index);
        int nima = index;
        //System.out.print(nima);
        
    }//GEN-LAST:event_jTable_productsMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try{
                Connection con = getConnection();
               // int index = jTable_products.getSelectedRow();
                //index = index+1;
                String value0 = txtid.getText();
                String value1 = txtname.getText();
                String value2 = txtprice.getText();
                String value3 = newquantity.getText();
                String value4 = txtstock.getText();
                
                
                //String value4 = txtname.getText();
                
                //String sql = "update products set product_name= '"+value1+"' , price = '"+value2+"' ,stock = '"+value3+"' ";
                int ops = Integer.parseInt(value3);
                int ops2 = Integer.parseInt(value4);
                int ans = ops + ops2;
                txtstock.setText(String.valueOf(ans));
                ////////////////////////////
                //update detais
                //txtname.setText(value1);
                //txtprice.setText(value2);
                ///////////////////////////
                
                PreparedStatement ps = (PreparedStatement) con.prepareStatement("update products set stock = '"+ans+"'where id ='"+value0+"'  ");
                PreparedStatement ps1 = (PreparedStatement) con.prepareStatement("insert into new_stock(product_id,stock) values(?,?) ");
                ps1.setString(1, txtid.getText());
                ps1.setString(2, newquantity.getText());
                newquantity.setText(null);
                
                
                
                ps.executeUpdate();
                ps1.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data updated");
                close();
                add_stock add5 = new add_stock();
                add5.setVisible(true);
        }
        catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }      
    }//GEN-LAST:event_jButton9ActionPerformed

    private void newquantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newquantityKeyPressed
        // TODO add your handling code here:
        if( evt.getKeyCode() == KeyEvent.VK_ENTER ){
            try{
                Connection con = getConnection();
               // int index = jTable_products.getSelectedRow();
                //index = index+1;
                String value0 = txtid.getText();
                String value1 = txtname.getText();
                String value2 = txtprice.getText();
                String value3 = newquantity.getText();
                String value4 = txtstock.getText();
                
                
                //String value4 = txtname.getText();
                
                //String sql = "update products set product_name= '"+value1+"' , price = '"+value2+"' ,stock = '"+value3+"' ";
                int ops = Integer.parseInt(value3);
                int ops2 = Integer.parseInt(value4);
                int ans = ops + ops2;
                txtstock.setText(String.valueOf(ans));
                ////////////////////////////
                //update detais
                //txtname.setText(value1);
                //txtprice.setText(value2);
                ///////////////////////////
                
                PreparedStatement ps = (PreparedStatement) con.prepareStatement("update products set stock = '"+ans+"'where id ='"+value0+"'  ");
                PreparedStatement ps1 = (PreparedStatement) con.prepareStatement("insert into new_stock(product_id,stock) values(?,?) ");
                ps1.setString(1, txtid.getText());
                ps1.setString(2, newquantity.getText());
                newquantity.setText(null);
                
                
                
                ps.executeUpdate();
                ps1.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data updated");
                close();
                add_stock add5 = new add_stock();
                add5.setVisible(true);
        }
        catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_newquantityKeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    
    //////////////////////////////////////////
    public ArrayList<products> getProductList(){
            
            ArrayList<products> productList = new ArrayList<products>();
            Connection con = getConnection();
            
            String query = "select * from products";
            
            Statement st;
            ResultSet rs;
            
        try {
            
            
            st = con.createStatement();
            rs = st.executeQuery(query);
            products product;
            
            while(rs.next()){
                product = new products(rs.getInt("id"),rs.getString("product_name"),rs.getInt("stock"),rs.getInt("price"),rs.getInt("discount"),rs.getString("warranty"),rs.getString("details"),rs.getInt("low_level"));
                productList.add(product);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(item_list.class.getName()).log(Level.SEVERE, null, ex);
        }
        return productList;
        
    }
    
    public void Show_products_in_Jtable(){
        ArrayList<products> list = getProductList();
        DefaultTableModel model = (DefaultTableModel)jTable_products.getModel();
        
        Object[] row =new Object[5];
        for(int i =0;i< list.size();i++){
            row[0] = list.get(i).getid();
            row[1] = list.get(i).getproduct_name();
            //row[2] = list.get(i).getprice();
            //row[2] = list.get(i).getquantity();
            row[2] = list.get(i).getprice();
            row[3] = list.get(i).getquantity();
            row[4] = list.get(i).getdetails();
            
            model.addRow(row);
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_products;
    private javax.swing.JTextField newquantity;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
   public void showitem(int index){
       txtid.setText(Integer.toString(getProductList().get(index).getid()));
       txtname.setText(getProductList().get(index).getproduct_name());
       txtstock.setText(Integer.toString(getProductList().get(index).getquantity()));
       txtprice.setText(Integer.toString(getProductList().get(index).getprice()));
   
   } 
   
   //THIS MAKING
   public void setnewstock(int index){
   
    // int result = ;                                                   //stock.getText());
   //txtstock.setText((txtnew.getText())+ (getProductList().get(index).getquantity()));
   }
    
}
