/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import com.mysql.jdbc.PreparedStatement;
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.function.Supplier;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class sales extends javax.swing.JFrame {
    int count = 0;
    /**
     * Creates new form sales
     */
    public sales() {
        initComponents();
        getConnection();
        Show_products_in_Jtable();
        showTime();
        showDate();
        add.setEnabled(false);
        btnprint.setEnabled(false);
        txtid.setEnabled(false);
        txtid.setEnabled(false);
        txtname.setEnabled(false);
        txtstock.setEnabled(false);
        newquantity.setEnabled(false);
        txtprice.setEnabled(false);
        txtdiscount.setEnabled(false);
        billnumber.setEnabled(false);
        txt_name.setEnabled(false);
        txt_search1.setEnabled(false);
        txttotal.setEnabled(false);
        txtpayment.setEnabled(false);
        txtbalance.setEnabled(false);
        
    }
    
    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        date.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                time.setText(s.format(d));
            }

        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        newquantity = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtstock = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_products = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bill_table = new javax.swing.JTable();
        txttotal = new javax.swing.JTextField();
        Discount = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtpayment = new javax.swing.JTextField();
        btnprint = new javax.swing.JButton();
        billnumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        strt_bill = new javax.swing.JButton();
        Discount1 = new javax.swing.JLabel();
        txtbalance = new javax.swing.JTextField();
        txtpayment1 = new javax.swing.JTextField();
        txt_search1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdiscount = new javax.swing.JTextField();
        btnpay = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Price                   :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 180, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Product Id            :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 170, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Product Name       :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 180, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Selling today        :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 170, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Available Quantity  :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 170, 40));

        txtname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 220, 40));

        txtid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 220, 40));

        newquantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newquantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newquantityKeyPressed(evt);
            }
        });
        jPanel2.add(newquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 590, 220, 40));

        txtprice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 220, 40));

        txtstock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(txtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 220, 40));

        txt_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_name.setText("search id here");
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nameKeyReleased(evt);
            }
        });
        jPanel2.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 410, 50));

        jTable_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "product_name", "price", "stock", "details"
            }
        ));
        jTable_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_productsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_products);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 60));

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setText("Back");
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 110, 40));

        add.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 640, 190, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("Clear");
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 640, 170, 40));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 640, 170, 40));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Log Out");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 640, 170, 40));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Metro Trade Center");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 50));

        time.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        time.setForeground(new java.awt.Color(0, 51, 255));
        time.setText("time");
        jPanel4.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 170, 30));

        date.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        date.setForeground(new java.awt.Color(51, 51, 255));
        date.setText("date");
        jPanel4.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 170, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 560, 70));

        bill_table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bill_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product", "Price", "Quantity", "Balance"
            }
        ));
        jScrollPane2.setViewportView(bill_table);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 560, 520));

        txttotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        jPanel2.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 260, 120, 40));

        Discount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Discount.setText("Payment");
        jPanel2.add(Discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 320, 110, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Total");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 240, 80, 80));

        txtpayment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaymentActionPerformed(evt);
            }
        });
        txtpayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpaymentKeyPressed(evt);
            }
        });
        jPanel2.add(txtpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 320, 120, 40));

        btnprint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnprint.setText("Print BiII");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel2.add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 550, 220, 40));

        billnumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(billnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 220, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("bill nimber            :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 170, 40));

        strt_bill.setText("Start a bill");
        strt_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strt_billActionPerformed(evt);
            }
        });
        jPanel2.add(strt_bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 210, 40));

        Discount1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Discount1.setText("Balance");
        jPanel2.add(Discount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 440, 110, 40));

        txtbalance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbalanceActionPerformed(evt);
            }
        });
        jPanel2.add(txtbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 440, 120, 40));

        txtpayment1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpayment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpayment1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtpayment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 320, 100, 40));

        txt_search1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search1ActionPerformed(evt);
            }
        });
        txt_search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search1KeyReleased(evt);
            }
        });
        jPanel2.add(txt_search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 410, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Discount              :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 180, 40));

        txtdiscount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(txtdiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 220, 40));

        btnpay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnpay.setText("Pay");
        btnpay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpayMouseClicked(evt);
            }
        });
        btnpay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnpayKeyPressed(evt);
            }
        });
        jPanel2.add(btnpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1043, 380, 210, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("start new bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 180, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        close();
        login lg = new login();
        lg.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        close();
        main mainpage = new main();
        mainpage.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_productsMouseClicked
        int index = jTable_products.getSelectedRow();
        showitem(index);
        int nima = index;
        //System.out.print(nima);

    }//GEN-LAST:event_jTable_productsMouseClicked

    private void newquantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newquantityKeyPressed
        // TODO add your handling code here:
        if( evt.getKeyCode() == KeyEvent.VK_ENTER ){
           ResultSet rs;
            Statement st;
            int num;
            try{
            Connection con = getConnection();
            // int index = jTable_products.getSelectedRow();
            //index = index+1;
            String value0 = txtid.getText();
            String value1 = txtname.getText();
            String value2 = txtprice.getText();
            String value3 = newquantity.getText();
            String value4 = txtstock.getText();
            String billid = billnumber.getText();
            String disco = txtdiscount.getText();

            //String value4 = txtname.getText();
            ////////////////////////////
            
            String query = " select low_level from products where id = '"+value0+"' ";
            
            st = con.createStatement();
            rs = st.executeQuery(query);
            products product;
            
            while(rs.next()){
                num = rs.getInt(1);
                int stock1 =Integer.parseInt(value4); 
                System.out.print(num +" and "+ stock1);
                if(num>=stock1){
                    JOptionPane.showMessageDialog(null, "Warning.Low items in stock");
                }
            }
            
            
            
            ///////////////////
            //PreparedStatement psnew = (PreparedStatement) con.prepareStatement(" select low_level from products where id = '"+value0+"' ");
            
            
            
            /////////////////////////////

            //String sql = "update products set product_name= '"+value1+"' , price = '"+value2+"' ,stock = '"+value3+"' ";
            int price = Integer.parseInt(value2);
            int ops = Integer.parseInt(value3);
            int ops2 = Integer.parseInt(value4);
            int disint  = Integer.parseInt(disco);
            int ans = ops2 - ops;
            int subprice = ops * (price-disint);
            count = count+ subprice;
            //System.out.print(count);
            txttotal.setText(String.valueOf(count));
            txtstock.setText(String.valueOf(ans));
            
            DefaultTableModel model = (DefaultTableModel)bill_table.getModel();
        model.addRow(new Object[]{txtid.getText(),txtname.getText(),txtprice.getText(),newquantity.getText(),String.valueOf(subprice)});
            int bill_id=0;
            PreparedStatement ps = (PreparedStatement) con.prepareStatement("update products set stock = '"+ans+"'where id ='"+value0+"'  ");
            PreparedStatement ps0 = (PreparedStatement) con.prepareStatement("update bill set total = '"+count+"'where id ='"+billid+"'  ");
            PreparedStatement ps1 = (PreparedStatement) con.prepareStatement("insert into bill_details(bill_id,product_id,items,subtotal) values(?,?,?,?)");
            ps1.setString(1, billnumber.getText());
            ps1.setString(2, txtid.getText());
            ps1.setString(3, newquantity.getText());
            ps1.setString(4, String.valueOf(subprice));
            
            
            

            ps.executeUpdate();
            ps0.executeUpdate();
            ps1.executeUpdate();
            newquantity.setText(null);
            JOptionPane.showMessageDialog(null, "Data updated");
            txt_name.setText(null);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        
        
            /*String value0 = txtid.getText();
            String value1 = txtname.getText();
            String value2 = txtprice.getText();
            String value3 = newquantity.getText();
            
            int ops = Integer.parseInt(value2);
            int ops2 = Integer.parseInt(value3);
            int ans = ops * ops2;
            
        
        DefaultTableModel model = (DefaultTableModel)bill_table.getModel();
        model.addRow(new Object[]{txtid.getText(),txtname.getText(),txtprice.getText(),newquantity.getText(),String.valueOf(ans)});
        */}
    }//GEN-LAST:event_newquantityKeyPressed

    private void txt_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyReleased
            ResultSet rs;
        try{
            Connection con = getConnection();
            
            String sql;
            sql = " select * from products where id = ? ";
            
            
            PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);
            ps.setString(1, txt_name.getText());
            rs = ps.executeQuery();
            
            if(rs.next()){
            String add1 = rs.getString("id");
            txtid.setText(add1);
            String add2 = rs.getString("product_name");
            txtname.setText(add2);
            String add3 = rs.getString("price");
            txtprice.setText(add3);
            String add4 = rs.getString("stock");
            txtstock.setText(add4);
            String discount = rs.getString("discount");
            txtdiscount.setText(discount);
            }
            
            
            
            
            
        }
        catch(Exception e){
            
        //////enter any exception message
        }
            
        
        
        
    }//GEN-LAST:event_txt_nameKeyReleased
    
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
            ResultSet rs;
            Statement st;
            int num;
            try{
            Connection con = getConnection();
            // int index = jTable_products.getSelectedRow();
            //index = index+1;
            String value0 = txtid.getText();
            String value1 = txtname.getText();
            String value2 = txtprice.getText();
            String value3 = newquantity.getText();
            String value4 = txtstock.getText();
            String billid = billnumber.getText();
            String disco = txtdiscount.getText();

            //String value4 = txtname.getText();
            ////////////////////////////
            
            String query = " select low_level from products where id = '"+value0+"' ";
            
            st = con.createStatement();
            rs = st.executeQuery(query);
            products product;
            
            while(rs.next()){
                num = rs.getInt(1);
                System.out.print(num);
                if(num>=Integer.parseInt(value4)){
                    JOptionPane.showMessageDialog(null, "Warning.Low items in stock");
                }
            }
            
            
            
            ///////////////////
            //PreparedStatement psnew = (PreparedStatement) con.prepareStatement(" select low_level from products where id = '"+value0+"' ");
            
            
            
            /////////////////////////////

            //String sql = "update products set product_name= '"+value1+"' , price = '"+value2+"' ,stock = '"+value3+"' ";
            int price = Integer.parseInt(value2);
            int ops = Integer.parseInt(value3);
            int ops2 = Integer.parseInt(value4);
            int disint  = Integer.parseInt(disco);
            int ans = ops2 - ops;
            int subprice = ops * (price-disint);
            count = count+ subprice;
            //System.out.print(count);
            txttotal.setText(String.valueOf(count));
            txtstock.setText(String.valueOf(ans));
            
            DefaultTableModel model = (DefaultTableModel)bill_table.getModel();
        model.addRow(new Object[]{txtid.getText(),txtname.getText(),txtprice.getText(),newquantity.getText(),String.valueOf(subprice)});
            int bill_id=0;
            PreparedStatement ps = (PreparedStatement) con.prepareStatement("update products set stock = '"+ans+"'where id ='"+value0+"'  ");
            PreparedStatement ps0 = (PreparedStatement) con.prepareStatement("update bill set total = '"+count+"'where id ='"+billid+"'  ");
            PreparedStatement ps1 = (PreparedStatement) con.prepareStatement("insert into bill_details(bill_id,product_id,items,subtotal) values(?,?,?,?)");
            ps1.setString(1, billnumber.getText());
            ps1.setString(2, txtid.getText());
            ps1.setString(3, newquantity.getText());
            ps1.setString(4, String.valueOf(subprice));
            
            
            

            ps.executeUpdate();
            ps0.executeUpdate();
            ps1.executeUpdate();
            newquantity.setText(null);
            JOptionPane.showMessageDialog(null, "Data updated");
            txt_name.setText(null);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        
        
            /*String value0 = txtid.getText();
            String value1 = txtname.getText();
            String value2 = txtprice.getText();
            String value3 = newquantity.getText();
            
            int ops = Integer.parseInt(value2);
            int ops2 = Integer.parseInt(value3);
            int ans = ops * ops2;
            
        
        DefaultTableModel model = (DefaultTableModel)bill_table.getModel();
        model.addRow(new Object[]{txtid.getText(),txtname.getText(),txtprice.getText(),newquantity.getText(),String.valueOf(ans)});
        */
    }//GEN-LAST:event_addActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txtpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaymentActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnprintActionPerformed

    private void strt_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strt_billActionPerformed
        // starting a bill from here:
        add.setEnabled(true);
        btnprint.setEnabled(true);
        newquantity.setEnabled(true);
        txtprice.setEnabled(true);
        txtdiscount.setEnabled(true);
        billnumber.setEnabled(true);
        txt_name.setEnabled(true);
        txt_search1.setEnabled(true);
        txttotal.setEnabled(true);
        txtpayment.setEnabled(true);
        txtbalance.setEnabled(true);
        
        
        int num;
        try{
            Connection con = getConnection();
            // int index = jTable_products.getSelectedRow();
            //index = index+1;
            //String value4 = txtname.getText();
            //String sql = "update products set product_name= '"+value1+"' , price = '"+value2+"' ,stock = '"+value3+"' ";
            //System.out.print(count);
            PreparedStatement ps = (PreparedStatement) con.prepareStatement("insert into bill(total) values(?)");
            int total=0;
            ps.setString(1, String.valueOf(total));
            
            ps.executeUpdate();
            ///////////////////////////////////////////////////////////////////////////////
            String query = "select * from bill";
            
            Statement st;
            ResultSet rs;
            
        try {
            
            
            st = con.createStatement();
            rs = st.executeQuery(query);
            products product;
            
            while(rs.next()){
                num = rs.getInt(1);
                billnumber.setText(String.valueOf(num));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(item_list.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_strt_billActionPerformed

    private void txtbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbalanceActionPerformed

    private void txtpayment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpayment1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpayment1ActionPerformed

    private void txt_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search1ActionPerformed

    private void txt_search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search1KeyReleased
        // TODO add your handling code here:
        ResultSet rs;
        try{
            Connection con = getConnection();
            
            String sql;
            sql = " select * from products where product_name = ? ";
            
            
            PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);
            ps.setString(1, txt_search1.getText());
            rs = ps.executeQuery();
            
            if(rs.next()){
            String add1 = rs.getString("id");
            txtid.setText(add1);
            String add2 = rs.getString("product_name");
            txtname.setText(add2);
            String add3 = rs.getString("price");
            txtprice.setText(add3);
            String add4 = rs.getString("stock");
            txtstock.setText(add4);
            }
            
            
            
            
            
        }
        catch(Exception e){
            
        //////enter any exception message
        }
    }//GEN-LAST:event_txt_search1KeyReleased

    private void btnpayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnpayKeyPressed
        // TODO add your handling code here:
        try{
            Connection con = getConnection();
            
            String total = txttotal.getText();
            String payment = txtpayment.getText();
            
            int totaln = Integer.parseInt(total);
            int paymentn =Integer.parseInt(payment);
            
            int bal = paymentn-totaln;
            txtbalance.setText(String.valueOf(bal));
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_btnpayKeyPressed

    private void btnpayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpayMouseClicked
        // TODO add your handling code here:
        try{
            Connection con = getConnection();
            
            String total = txttotal.getText();
            String payment = txtpayment.getText();
            
            int totaln = Integer.parseInt(total);
            int paymentn =Integer.parseInt(payment);
            
            int bal = paymentn-totaln;
            txtbalance.setText(String.valueOf(bal));
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_btnpayMouseClicked

    private void txtpaymentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpaymentKeyPressed
        // TODO add your handling code here:key press/////////////////
        if( evt.getKeyCode() == KeyEvent.VK_ENTER ){
            try{
            Connection con = getConnection();
            
            String total = txttotal.getText();
            String payment = txtpayment.getText();
            
            int totaln = Integer.parseInt(total);
            int paymentn =Integer.parseInt(payment);
            
            int bal = paymentn-totaln;
            txtbalance.setText(String.valueOf(bal));
            
        }catch(Exception e){
            
        }
        }
        
        
        
        //////////////////////////
    }//GEN-LAST:event_txtpaymentKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //close();
        sales_admin2 add = new sales_admin2();
        add.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    /////////////////////////////////////////
    public ArrayList<products> getProductList(){
            
            ArrayList<products> productList = new ArrayList<products>();
            Connection con = getConnection();
            
            String query = "select * from products";
            
            Statement st;
            ResultSet rs;
            
        try {
            
            
            st = con.createStatement();
            rs = st.executeQuery(query);
            products product;
            
            while(rs.next()){
                product = new products(rs.getInt("id"),rs.getString("product_name"),rs.getInt("stock"),rs.getInt("price"),rs.getInt("discount"),rs.getString("warranty"),rs.getString("details"),rs.getInt("low_level"));
                productList.add(product);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(item_list.class.getName()).log(Level.SEVERE, null, ex);
        }
        return productList;
        
    }
    
    public void Show_products_in_Jtable(){
        ArrayList<products> list = getProductList();
        DefaultTableModel model = (DefaultTableModel)jTable_products.getModel();
        
        Object[] row =new Object[5];
        for(int i =0;i< list.size();i++){
            row[0] = list.get(i).getid();
            row[1] = list.get(i).getproduct_name();
            
            row[2] = list.get(i).getprice();
            row[3] = list.get(i).getquantity();
            row[4] = list.get(i).getdetails();
            
            model.addRow(row);
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Discount;
    private javax.swing.JLabel Discount1;
    private javax.swing.JButton add;
    private javax.swing.JTable bill_table;
    private javax.swing.JTextField billnumber;
    private javax.swing.JButton btnpay;
    private javax.swing.JButton btnprint;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_products;
    private javax.swing.JTextField newquantity;
    private javax.swing.JButton strt_bill;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_search1;
    private javax.swing.JTextField txtbalance;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpayment;
    private javax.swing.JTextField txtpayment1;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtstock;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
   public void showitem(int index){
       txtid.setText(Integer.toString(getProductList().get(index).getid()));
       txtname.setText(getProductList().get(index).getproduct_name());
       txtprice.setText(Integer.toString(getProductList().get(index).getprice()));
       txtstock.setText(Integer.toString(getProductList().get(index).getquantity()));
   
   } 
   
   //THIS MAKING
   public void setnewstock(int index){
   
    // int result = ;                                                   //stock.getText());
   //txtstock.setText((txtnew.getText())+ (getProductList().get(index).getquantity()));
   }
   
   public Connection getConnection(){
        Connection con = null;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stockmgt","root","");
            //JOptionPane.showMessageDialog(null, "connected");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(add_item.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "not connected");
            return null;
        }
    }
}
